### ISSUE TITLE
Change "current_page_ancestor" to "current-page-ancestor" 

### ISSUE THREAD

**Issue by kirandash** [Automattic/_s#1031]
Underscores should be hyphens. On style.css line 608.

**Comment by msroberts** [comment]
For historical reasons, WordPress' default page menu uses underscores rather than hyphens in its class names.

https://developer.wordpress.org/reference/functions/wp_list_pages/#menu-item-css-classes

**Comment by AshboDev** [comment]
@kirandash I agree with you 100%. For classes and ID's, should always be hyphens (as per CSS itself) however WordPress seems to have some fascination with underscores for classes. I can't see this changing sadly (As much as I, and others would like it to!) :(

**Comment by karmatosed** [comment]
We can't change this as a core class.

**Comment by realjjaveweb** [comment]
Did anybody do anything with this? Because I've recently on latest WP encountered a very strange error in submenu parent `li` that even though most of them have `current-page-ancestor`, suddenly, one has `current_page_ancestor` - which made me notice since the CSS was obviously not working. Could anybody please link MR if they know? I only found this thread...
