### ISSUE TITLE
Build Failed comments.php

### ISSUE THREAD

**Issue by heanfig** [Automattic/_s#1067]
Missing singular placeholder, needed for some languages.
https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals

**Comment by jrfnl** [comment]
See #1012

**Comment by davidakennedy** [comment]
This should have been fixed with the merge of #1012, but seems to be still broken. Will investigate further. 😄

**Comment by jrfnl** [comment]
@davidakennedy FYI:

See #1079 - at least part of it will be fixed by PR #1099 and #1100.

The other issue is that WPCS is currently not - yet - compatible with PHPCS 3.x which came out in May. An attempt is being made to make WPCS compatible with both PHPCS 2.x as well as 3.x, but this is not fixed yet: see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/718

The current travis script pulls in PHPCS `master` which has now become the 3.x branch. To get the build to pass again, - for now - PHPCS should be pulled as `2.9` (= the 2.x branch).

On that note, the PHPCompatibility standard *will* soon become compatible with both PHPCS 2.x as well as 3.x, however, a fix is pending there to fix compatibility with composer which will be a breaking change and will mean that the travis script will need a minor change again. See: https://github.com/wimg/PHPCompatibility/pull/446

**Comment by davidakennedy** [comment]
Thanks for the explanation @jrfnl! Really helpful, especially as we're not following those changes very closely. I've switched branches on PHPCS as you suggested and got your other, related PRs merged. The build is passing now! 🚀 

I'll probably open an issue to remind us to switch back to `master` whenever appropriate.

Thanks again for all your work here!

**Comment by jrfnl** [comment]
@davidakennedy No worries. Glad it is sorted again for now.

If I remember at the time, I'll send in PRs to `_s` for the relevant changes for WPCS 0.12.0 / WPCS PHPCS 3.x compat and the PHPCompatibility Composer changes if and when my PRs for these changes in WPCS/PHPCompatibility get merged.

If the build is breaking again on PHPCS and I haven't yet send in any PRs, feel free to ping me here or on Slack and I'll help you get it sorted.
