### ISSUE TITLE
Move font-size to html element

### ISSUE THREAD

**Issue by 11bits** [Automattic/_s#1071]
I suggest move font-size from body to html element. In this way, when you change font-size all elements with rem units also change accordingly.

Example:

```
html {
     font-size: 16px;
}

h1 {
    fon-size: 2rem; /* 32px */
}

@media screen and (min-width: 52rem) {
	html {
		font-size: 18px;
	}
}
```

In this example when font-size changes to 18px, h1 has a value of 36px.

**Comment by pixelstrolch** [comment]
I learned it's not best accessibility practise to use pixels for font size. It overrides the size which the user defines in the browser settings. Although there will be more users who change the zoom instead of the font size, I guess it would be better to use 100% and 112.5%.

The technique looks interesting indeed. However, I'm not sure it is good to use it in a starter theme. If not everything is meant to scale equally, it might looses its benefits, because you would have to use more media queries on other places as well.

I found the article "[EM vs REM vs PX](http://engageinteractive.co.uk/blog/em-vs-rem-vs-px)" quite helpful.

**Comment by slushman** [comment]
@pixelstrolch _s currently uses pixels (16px) to set the default font size, but on the body element (line 270 in style.css). @11bits is recommending moving that to the html element instead.

For setting font sizes on other elements, you're absolutely correct, they should be set with either EMs or REMs to allow for resizing.

**Comment by pixelstrolch** [comment]
@slushman This is the fallback of 1rem, because most browsers default font size is 16px. The px size will be overwritten in all modern browsers. 

If you give the html element a px font size the browser font size setting won't work anymore.

**Comment by 11bits** [comment]
I see the accessibility issue that mention @pixelstrolch and yes, the solution would be using % or rem instead of pixels in the root element.

```
html {
     font-size: 1rem;
}

@media screen and (min-width: 52rem) {
	html {
		font-size: 1.125rem;
	}
}
```

I have read the article and is a good summary of font units, but curiously enough if you check its code they use pixels in the html element.

About the second issue, I like everything scale when the font size changes but I understand that is a personal preference and it depends on the project.

**Comment by 11bits** [comment]
Thanks for your comments, I close this issue.
