### ISSUE TITLE
Better user experience

### ISSUE THREAD

**Issue by LebCit** [Automattic/_s#1082]
Hello,

While working on a theme, I've realized that the `_s_posted_on()` function could be a little bit modified for an automatic better user experience.
This is what I suggest :
```
if ( ! function_exists( '_s_posted_on' ) ) :
/**
 * Prints HTML with meta information for the current post-date/time and author.
 */
function _s_posted_on() {
	$time_string = '<time class="entry-date published updated" datetime="%1$s">%2$s</time>';
	if ( get_the_time( 'U' ) == get_the_modified_time( 'U' ) ) {
		$time_string = '<time class="entry-date published" datetime="%1$s">%2$s</time>;		
		$posted_on = sprintf(
			esc_html_x( 'Posted on %s', 'post date', '_s' ),
			'<a href="' . esc_url( get_permalink() ) . '" rel="bookmark">' . $time_string . '</a>'
		);
	} else {
		$time_string = '<time class="updated" datetime="%3$s">%4$s</time>';		
		$posted_on = sprintf(
			esc_html_x( 'Update on %s', 'post date', '_s' ),
			'<a href="' . esc_url( get_permalink() ) . '" rel="bookmark">' . $time_string . '</a>'
		);
	}
	$time_string = sprintf( $time_string,
		esc_attr( get_the_date( 'c' ) ),
		esc_html( get_the_date() ),
		esc_attr( get_the_modified_date( 'c' ) ),
		esc_html( get_the_modified_date() )
	);
	$byline = sprintf(
		esc_html_x( 'by %s', 'post author', '_s' ),
		'<span class="author vcard"><a class="url fn n" href="' . esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ) . '">' . esc_html( get_the_author() ) . '</a></span>'
	);
	echo '<span class="posted-on">' . $posted_on . '</span><span class="byline"> ' . $byline . '</span>'; // WPCS: XSS OK.
}
endif;
```
What do you think ?
Wouldn't it be better to give common WP users an out of the box (unknown) functionality ?

Thanks a lot for all your efforts.

**Comment by grappler** [comment]
The updated line is not shown in the default CSS https://github.com/Automattic/_s/blob/master/style.css#L761

I think the reason for the updated date is for SEO reasons so that the Google know when the post was updated. It normally makes more sense to add an update comment to a post so that the reader knows what is changed.

Personally I might update a post after publishing it and it does not really interest the reader when if I updated the post 5 minutes after publishing the article. 

It also comes down to the design of your theme.

**Comment by LebCit** [comment]
Hello, I'm aware of the `.updated:not(.published) {display: none;}` line.
If you remove this CSS def.  with the actual `_s_posted_on()` function, you'll get two nice post's date along with each other...

> Personally I might update a post after publishing it and it does not really interest the reader when if I updated the post 5 minutes after publishing the article.
It's always better to know the last time a post was updated **to rely or not** on the information provided inside it.
My suggestion is to give **common WP users** (not developers who knows how to tweak everything) a better WP experience.
Thanks.

**Comment by mrwweb** [comment]
This also may have been intended to resolve hAtom errors from Google Search Console. I know that's been an issue in the past.

**Comment by davidakennedy** [comment]
Thanks opening this issue @LebCit! I really like the code approach here.

That said, this isn't something I see going into _s. Only because as @grappler said, it comes down to the theme, and most don't need this type of "updated" entry meta. So it's better to leave that to the individual theme designer.

> This also may have been intended to resolve hAtom errors from Google Search Console. I know that's been an issue in the past.

This is correct.
