### ISSUE TITLE
Remove POT file

### ISSUE THREAD

**Issue by grappler** [Automattic/_s#1209]
The pull request #1208 from @Smartik89 prompted me think if we still need a POT file.

- WordPress.org now automatically adds all of the theme's strings to translate.wordpress.org for translation so the pot file is not needed anymore.
- Most themes have enough changes made to them that they need to regenerate the POT file so it is not up to date anymore.
- Creating a POT has become a lot easier and there are many tutorials how to do so.

@davidakennedy How does WordPress.com handle translations?

**Comment by samikeijonen** [comment]
Just noting that `_s` is used a lot for clients sites also outside of wp.org or wp.com. But I'm fine removing it since it needs to regenerate anyway.

Only reason I see keeping POT file is for educating developers using `_s`.

**Comment by Smartik89** [comment]
When I saw this file I was thinking the same as @grappler . Anyway, removing it may not be required but changing the name to use theme's slug is really necessary.

**Comment by jrfnl** [comment]
Please do not remove the `.pot` file.

> * WordPress.org now automatically adds all of the theme's strings to translate.wordpress.org for translation so the pot file is not needed anymore.

Only a fraction of all themes out there are published on wp.org, so that really should not be a consideration.

> * Most themes have enough changes made to them that they need to regenerate the POT file so it is not up to date anymore.
> * Creating a POT has become a lot easier and there are many tutorials how to do so.

From an education perspective, having the file there does a lot of good making devs aware of internationalization and localization. That they need to regen is a given, but again more an education issue than a reason to remove the file.

**Comment by grappler** [comment]
> Anyway, removing it may not be required, but changing the name to use theme's slug is really necessary.

The file does get automatically renamed when downloading from https://underscores.me/

An alternative would be to remove the POT file from git but automatically generate the file when downloading from https://underscores.me/

**Comment by philiparthurmoore** [comment]
Git is supposed to contain all the parts that make up Underscores. I don't see the benefit of overcomplicating this and taking that file out. It's pretty important for multilingual sites.

**Comment by philiparthurmoore** [comment]
Anybody else have an opinion on this? Mine hasn't changed.

**Comment by justintadlock** [comment]
Ditto on what's pretty much been said.  Underscores should come with a POT file since it's not a project for building WordPress.org-only themes.  Even on WordPress.org, I think it's good practice to include the file in the theme package.  You don't know who's getting your theme and in what context they're using it.

**Comment by Ismail-elkorchi** [comment]
I am going to close this issue as the consensus here was not to remove the pot file.

In https://github.com/Automattic/_s/pull/1395 I added to composer a command `make-pot` which relies on [wp-cli/i18n-command](https://github.com/wp-cli/i18n-command) to ease the regeneration of the POT file, and used it to update `languages/_s.pot`.
