### ISSUE TITLE
Create _s Parent and _s Child

### ISSUE THREAD

**Issue by Ismail-elkorchi** [Automattic/_s#1233]
_s is not a parent theme as stated in the project's description : 

> I'm a theme meant for hacking so don't use me as a Parent Theme

Moreover, the conclusion that can be drawn from this issue https://github.com/Automattic/_s/issues/1059 supports what is already stated in description.

But, there are some opened issues like https://github.com/Automattic/_s/issues/1116, https://github.com/Automattic/_s/issues/1075 and https://github.com/Automattic/_s/issues/1141 which discuss making changes to better support using _s as a parent theme.

The problem is that the decisions taken above contradict the project's description, and drives the project away from its objectives.

What I said so far is not the only reason why I think that this issue should be discussed seriously. There are a lot of developers that seek to use _s as a parent theme, which a simple search in the project's issues can demonstrate. Wordpress itself allow theme developers to use not only a standalone theme, but also parent/child theme.

IMHO the Wordpress community will benefit a lot from creating a _s parent/child variants, as these two new projects will help guide and educate a big part of the community. This will also help _s focus on its purpose (being a starter standalone theme), and become simpler by removing all the code intended for child theme overloading.

**Comment by grappler** [comment]
I am not fully sure I understand the point you are trying to make. I would like to clarify 
> I'm a theme meant for hacking so don't use me as a Parent Theme

This line means you should not use `_s`  as is and create child themes to change the design but you should use `_s` as a base and build upon it.

The w.org requirements state that all themes should be child theme compatible meaning that the themes should allow child themes to be created. I support this and make sure that `_s` is child theme compatible.

#1116 does not seem to go against that principle. It still needs a PR.

As for #1141 the functions were first introduced in WP 4.7. We like to have new features in at least two versions of WP as that allows the adoption to increase. Once WP 4.9 is released in the middle of the month we can look into merging that PR.

#1075 is a difficult topic with people with strong views on both sides.

I think it is best to discuss the issues in their own issues instead of one big issue.

Let me know if I understood you incorrectly.

**Comment by tyrann0us** [comment]
Just for the record: I'm using `_s` as a parent theme in all of our WordPress projects. Using [Bedrock](https://roots.io/bedrock/), I added `_s` as a repository (which is ignored by `.gitignore`).

This workflow helps me to keep the main, project related (child) theme as small as possible, without the need to add all the theme files that stay untouched to the repository (e. g. the entire `inc` folder).

The only drackback is that I need to change the `_s`'s (fake) `version` in my `composer.json` with every commit because there are no git tags. _(This sometimes causes errors when running `composer update`; I still have to figure out a better workflow.)_

**Comment by grappler** [comment]
@tyrann0us Interesting! BTW could you not use `dev-master` for the version instead.

**Comment by tyrann0us** [comment]
> @tyrann0us Interesting! BTW could you not use dev-master for the version instead.

Since `_s` is missing a `composer.json` I need to include it as a [`package`](https://getcomposer.org/doc/05-repositories.md#package-2) repository (see https://github.com/Automattic/_s/issues/921#issuecomment-213949204). Setting `dev-master` as `version` does not work to my knowledge.

Composer states:
> Composer will not update the package unless you change the version field.

**Comment by laurelfulford** [comment]
Thanks for creating this issue, @Ismail-elkorchi! 😄 

Making separate parent/child variants of the project sounds like a good idea, but seems like something that would be better suited to a fork of _s. 

Echoing @grappler, in _s we're trying to make sure it's a good base for folks to build themes that are child theme compatible. But anyone is welcome to fork and alter the theme as it would suit specific needs, like as a child theme starter, or without the child theme compatible code!
