### ISSUE TITLE
Implement KSS Documentation for elements in stylesheet

### ISSUE THREAD

**Issue by merrillcook0** [Automattic/_s#1236]
Implementation of [KSS-style documentation](https://github.com/kneath/kss) for current css and scss components in _S so that users may continue to build on documentation instead of having to backtrack and implement KSS for all elements already included in the theme as well as new css elements.

**Comment by grappler** [comment]
Hi @merrillcook0

Thank you for the issue. I have personally not heard of KSS-style documentation before but that could be just because I am not a CSS geek.

For me to make a decision I would need to see how it is implemented. Do you have any examples where you have used it with `_s`?

Are there any other reasons why KSS-style documentation should be implemented other than it saving you and other time implementing it again in new themes?

My concern is how much noise does it add to new users who are starting developing their first theme. We want to keep the barrier to entry as low as possible.
