### ISSUE TITLE
Archive Automattic/underscores.me

### ISSUE THREAD

**Issue by szepeviktor** [Automattic/_s#1349]
Please archive the other repo and move [relevant issues](https://github.com/Automattic/underscores.me/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) here.
Thank you.

**Comment by crunnells** [comment]
Hey @szepeviktor, as I'm sure you're aware, that repo (`automattic/underscores.me) is not for theme issues with `_s`, but for the generator web site. Since it serves a separate function from this repo, we're not going to archive that repo unless we take down the web site. However, it's a good point that any `_s` specific issues _should_ be moved over to this repo. If you'd like to tackle that, it would be much appreciated!

**Comment by szepeviktor** [comment]
@crunnells I think almost everybody thinks that the starter theme's repo is `automattic/underscores.me`

How about adding ISSUE_TEMPLATE.md to warn future contributors about this fact?

**Comment by szepeviktor** [comment]
And setting the GitHub repo description would be also a nice thing.

**Comment by crunnells** [comment]
> I think almost everybody thinks that the starter theme's repo is `automattic/underscores.me`

Don't be that sure ;-)

Thanks for the feedback tho; I'll work on this to point people to the correct repo.
