### ISSUE TITLE
Bootstrap's new Responsive Font Sizes AKA RFS from v.4.3+ conflicts with font-size mixin

### ISSUE THREAD

**Issue by pentamint** [Automattic/_s#1358]
**Mixin Conflict**
Bootstrap's new versions starting from 4.3.0+, released a new mixin called Responsive Font Sizes  aka RFS.

The existing values inside the mixin "@include font-size();" will be calculated by the new RFS mixin - which makes all font sizes SUPER SMALL.

For now, I have reinstalled Bootstrap 4.2.1 and the problem goes away.

**Comment by PixemWeb** [comment]
> **Mixin Conflict**
> Bootstrap's new versions starting from 4.3.0+, released a new mixin called Responsive Font Sizes aka RFS.
> 
> The existing values inside the mixin "@include font-size();" will be calculated by the new RFS mixin - which makes all font sizes SUPER SMALL.
> 
> For now, I have reinstalled Bootstrap 4.2.1 and the problem goes away.

Note: make a backup of your files before making critical changes.
Since you're using bootstrap, you could always remove the font-size mixin that comes with underscores. I use bootstrap with underscores myself and I remove the duplicate code or unneeded code for scss/css from underscores. I use Gulp with Sass to process the files which will generate the new style sheet once my changes are made.
Note:  you should make note of any classes you will need that are WordPress specific and make sure to keep those. 
I hope this helps.

**Comment by itrogers** [comment]
I had the same issue with font sizes being super small after replacing the the default underscores `font-size()` mixin with the one included in bootstrap. In order to make the sizes normal again you simply need to add in `rem` inside all of the mixin calls (which is required per the RFS docs: https://github.com/twbs/rfs). So `@include font-size(1)` becomes `@include font-size(1rem)`.... which fixed the issue for me.

**Comment by Ismail-elkorchi** [comment]
@pentamint Thank you for the issue report. Closing as this isn't a problem with `_s` itself
