### ISSUE TITLE
'posted_on' and 'by' translation 

### ISSUE THREAD

**Issue by guillaumegautier** [Automattic/_s#1365]
Hello, I know those two strings have already been corrected but...
_s is a theme meant to be hacked and I added some new strings for translation. So i added my sources in Poedit, my new strings appear and are translated but the two 'Posted_on %s' and 'by %s' are detected but not working.
Is there another way to code them so the generated .po and .mo work ?

Of course if I use .pot, it works but I dont have my new translatable strings. 

![Capture d’écran 2019-07-09 à 17 20 16](https://user-images.githubusercontent.com/10887041/60901254-ecd49300-a26d-11e9-8326-771e71047519.png)

**Comment by Ismail-elkorchi** [comment]
Thank you @guillaumegautier for the issue report.

It seems that the .pot file wasn't updated since https://github.com/Automattic/_s/pull/1119. This PR https://github.com/Automattic/_s/pull/1395 should address this.

If you use the latest version of `_s` and you have composer installed, you can update the .pot file after modifying the theme's text by running the commands `composer install` then `composer make-pot` in the terminal.
