### ISSUE TITLE
Underscores License to GPL v3

### ISSUE THREAD

**Issue by amyunus** [Automattic/_s#140]
I want to ask about underscores license. Is it possible to license underscores to GPL v3? I find difficulties to combine this starter theme to any component that has APL v2. Thanks.

**Comment by pedro-nonfree** [comment]
> Closing this for now. It's something we may revisit at a later date.

Enough time to revisit? If not, at least explain why is good the actual license.

We are experimenting licensing issues. We would like to do a project in AGPLv3 (which I think is great in general), and we cannot do it because is not GPLv3 or GPLv2+

I think GPLv2 is bad for a web project because these days we are seeing lots of different integrations, and it's better to switch to a more "compatible" license. Linux kernel (GPLv2) is another world.

**Comment by philiparthurmoore** [comment]
@pedro-nonfree Underscores is licensed as `GNU General Public License v2 or later`. A derivative work that you create with it can be licensed as GPLv2 or GPLv3. If the theme were licensed as GPLv3, developers would not have that same freedom. We would be stuck with GPLv3, as you cannot go from GPLv3 to GPLv2 but you can go from `GNU General Public License v2 or later` to GPLv3.
