### ISSUE TITLE
Underscores seems to be a little outdated

### ISSUE THREAD

**Issue by fabio-blanco** [Automattic/_s#1511]
A lot of things in this project are getting a little bit outdated and it seems that there is no merge since a year ago despite the fact that there are some pull requests that fixes some issues that could be reviewed. 
With the version 5.9 of the WordPress scheduled to be released in the next month and all the efforts to bring full site editing to be the next "recommended way to create themes" in WordPress will the _s starter theme be abandoned by the Automatic folks?

**Comment by ClarusDignus** [comment]
Going forward, I'll be using the Twenty-Twenty Two for WordPress 5.9 as a parent theme instead of using Underscores as a starter theme.

https://make.wordpress.org/core/2021/10/06/introducing-twenty-twenty-two/

https://www.youtube.com/watch?v=XvEG9XWD4JI

WordPress is taking a big step forward in terms of making page and site building part of its core functionality. It makes more sense to me to invest in the learning curve to reverse engineer WordPress's new official block theme (Twenty-Twenty Two) rather than clinging to what's effectively an abandoned and near obsolete starter theme (Underscores).

An Underscores successor might emerge in several months time in the form of a stripped down version Twenty-Twenty Two, i.e., stripped down enough to be considered a starter theme rather than a parent theme.

Twenty-Twenty Two is a block theme like the Astra theme or Elementor's Hello theme. Block themes are the way forward. We're at a transitional point and need to adapt.

https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/

It's a positive step forward. Making page and site building part of WordPress's core functionality eliminates the requirement and cost of premium page and site builders like Elementor.

The new paradigm is modifying themes using WordPress's front-end customizer rather than modifying the theme files. This is anathema to Underscores.

**Comment by fabio-blanco** [comment]
> It's a positive step forward.
I am aware of this movement as mentioned in the question.

> Making page and site building part of WordPress's core functionality eliminates the requirement and cost of premium page and site builders like Elementor.

That's a requirement I already don't have. The requirement I have is to be able to tweak the source code myself, be it a traditional or a block theme.

> The new paradigm is modifying themes using WordPress's front-end customizer rather than modifying the theme files. 

I believe that there are things one can achieve just by having full control of the system and that is the beauty of the open source code. It allows you to have this full control. This new paradigm you mention is nice from the perspective of the default user but as a power user I have other needs. 

I'm more interested in developing themes and plugins than designing a web site. There are problems that are better solved by a starter theme than by the WordPress front-end customizer.

I'm not saying that the full site editing approach is bad. I'm just saying that a starter theme like Underscores (or a Block Theme version of it) is still useful. If you need to hit a nail you will use a hammer but if you need to tighten a screw you will use a screwdriver. Each tool has its own use and function.

**Comment by fabio-blanco** [comment]
I'm closing this issue because I've discovered this project is no longer maintained. To know more see #1470
