### ISSUE TITLE
Sass and style.css: We need a contributor workflow.

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/_s#615]
It occurs to me that I am utterly confused with the proper workflow for patches and pull requests now that Sass is in place. Some PRs alter `style.css` while some PRs alter the Sass alternatives. @karmatosed and I had a little chat and it appears that we need to update our contributor guidelines so that people are submitting PRs in the right way and also primary _s collaborators know what to look for when PRs come in. @obenland, I see https://github.com/Automattic/_s/commit/b76f394a79b64075a0e82e7642b73b9c7d68ce27 only includes Sass stuff but no `style.css` stuff. And https://github.com/Automattic/_s/pull/605, which is a good fix, only includes `style.css` stuff but no Sass stuff. Very, very confused here, and feeling insecure about parity between Sass and the style file for the non-Sass folk.

How should we be handling this moving forward?

**Comment by iandunn** [comment]
After sending in a few PRs this week, I can attest to how much of a pain it is to apply the changes to both SASS and vanilla CSS. It adds a significant amount of work, and the prospect of having to jump through those extra hoops for future PRs definitely adds a motivational barrier.

I know @obenland said that the maintainers would bear that burden, but then I'd just feel guilty about being lazy and pushing that work off onto them instead of doing it myself. I also worry that over time the extra workload would make maintainers less likely to merge PRs, and make contributors less likely to become maintainers.

If the goal is to continue supporting vanilla CSS while also adding LESS, then I think having separate branches for each might be the most sane approach. Pick one version to be `master` -- my vote would be for SASS -- and then have the other two versions live in their own separate branches. 

Each branch could have it's own group of maintainers, and contributors could send PRs to whichever branch they want. Whenever commits are merged to one branch, the maintainers of the other branches merge them in, making the necessary adjustments. Underscores.me could be updated to pull from the appropriate branch based on which version the user requested.

That way, contributors never have to do any extra work, and the extra work that needs to be done by maintainers is spread around, instead of all landing on the person merging the PR. Most PRs would probably be sent to the SASS branch, so most of the extra work would be done by the LESS and vanilla CSS maintainers, which seems appropriate, since they're the ones who want the extra versions in the first place.

**Comment by drrobotnik** [comment]
As much as I love SASS, the beauty of _s is how lean it is. It shouldn't take developers long to split out the baseline css file into separate less/sass files manually.

**Comment by szyam** [comment]
For what its worth, I kinda agree with @drrobotnik . I start with _s for my projects and I also use sass, but the way the scss partials are broken down don't really suit my needs. I usually just throw in my own sass folder from my html projects anyways. I also gut most of the html, so I say keep it as lean as possible, since most dev's (I'm just guessing here) are adapting it to their needs/workflow.

**Comment by WPAddiction** [comment]
I like the idea of creating a new branch and not merging it until the CSS, SASS, and Less (when it gets added) are all updated; I think that alone would motivate people to update all three. Plus I don't think a commit should ever mix file types. I personally commit PHP and SASS separately so I can cherry pick commits to update other projects. I maintain a starter theme based on _s and it's nice to be able to cherry pick commits when appropriate, but it adds an extra step if SASS and CSS are committed together. Also since most of the SASS is my own it also makes it difficult to cherry pick a commit that has both SASS and PHP updates if I only want the PHP. Not to get off topic there, but those are my thoughts and experiences, although I am relatively new to GitHub.

**Comment by davidyezsetz** [comment]
I think @obenland is correct that this can only be maintained by collaborators. Since the topic of this issue however suggests a change in the contribution workflow, I'd like to propose that any css related PR includes a comment what's included and what's not. E.g. PR#123 is accompanied by "Only added SASS". That way collaborators can quickly see where additional work is needed and add e.g. a tag "css needed". If needed I can prepare a PR to include this into contributing.md

**Comment by iandunn** [comment]
> I'd like to propose that any css related PR includes a comment what's included and what's not

Wouldn't that be obvious from [the Files Changed tab](https://github.com/Automattic/_s/pull/680/files) on the PR?

**Comment by davidyezsetz** [comment]
@iandunn if you only change two files, yes. Once you hit a certain numbers of files changed this can get tedious though [e.g.](https://github.com/Automattic/_s/pull/682/files). Truth be told this only slightly eases the pain on the collaborators (if at all), but if it's agreed that collaborators are responsible for maintaining parity among css, scss and possibly other preprocessors, I can't think of other changes to improve the current workflow. 
I guess it comes down to the size of your average PR wether it is reasonable to make contributing a bit harder to make maintaining a bit easier. 
Quite possibly the answer to this issue is that there is none and it can be closed, but since it was getting stale I thought I'd give it a whack.

**Comment by iandunn** [comment]
Er, sorry, I should have been more specific; If you click the `{x} Files Changed` link at the top it'll reveal a list of them all, so you don't have to scroll through the whole page.

**Comment by davidyezsetz** [comment]
Neat. Even after 3 months of excessive code reviews solely via GitHub, I have managed not to see this. If you excuse me I will check my closet for a big clown hat to wear for the rest of the day.
It would appear that this really comes down to collaborators hoping for the best and doing the rest.

**Comment by iandunn** [comment]
hehe, no worries, it's easy to miss. If we had to put on clown hats every time we made trivial mistakes then I'd never be able to take mine off :)

**Comment by karmatosed** [comment]
This seems to have stalled a bit, that's ok as things happen. I do think it is up to the contributors to merge and in both places. I have a plan to make the Sass easier in the near-future soon (more to come on that). For now, I think in general we could perhaps have better documentation, but the bottom line is the people merging will be doing the changes in both places if a PR doesn't.

It's worth noting a slight mis-conception raised. Sass doesn't produce undocumented code. Sass is just a pre-processor. It creates as good or bad as you send to it. You can send well commented, organised CSS and get it out in end.
