### ISSUE TITLE
Posted on date doesn't show

### ISSUE THREAD

**Issue by leanda** [Automattic/_s#625]
Having a strange issue where I can't get the posted on date to appear unless I go in and update the post. Anyone else had this problem?

Thanks

**Comment by susanlangenes** [comment]
I'm commenting on this because I've been running into the same exact problem.  I'm looking at function _s_posted_on() in /inc/template-tags.php and I don't see anything that would indicate that the intended behavior is to only show the posted on date if post has been updated (or if there exists a revision), but this is what's happening consistently.  Help?!

**Comment by emiluzelac** [comment]
`_s_posted_on()` doesn't have visible updates. 

As far as the latest function itself https://github.com/Automattic/_s/blob/master/inc/template-tags.php#L72 it works as intended :)

This part is visible:
```
<time class="entry-date published" datetime="2015-03-25T14:31:56+00:00">March 25, 2015</time>
```

while updates are not:

```
<time class="updated" datetime="2015-04-04T16:26:17+00:00">April 4, 2015</time>
```

You can show updates too if you change the following line: https://github.com/Automattic/_s/blob/master/style.css#L747

```
.byline,
.updated:not(.published) {
	display: none;
}
```

**Comment by susanlangenes** [comment]
OH.  Ok, I see what's happening.  I didn't have that line 

    .byline,
    .updated:not(.published) {
	    display: none;
    }
I had simply: .updated {display: none} - likely came from an earlier version of the stylesheet or something I did.  

Thanks for your help :)
