### ISSUE TITLE
Add fonts enqueue to functions.php

### ISSUE THREAD

**Issue by hugobaeta** [Automattic/_s#728]
More often than not, at least for me, I have the need to add either a GoogleFont or a Typekit font to my themes. Would be great to have a recommended way to do this in the functions.php, even if commented out.

I know Automattic themes have this long crazy function to register Google fonts. I think we could have a simplified version in _s, that could be used both for GoogleFonts or to paste in the Typekit code.

For GoogleFonts I usually do:

```
function _s_load_fonts() {
	wp_register_style('googleFonts', 'http://fonts.googleapis.com/css?family=Montserrat');
	wp_enqueue_style( 'googleFonts');
}
add_action('wp_print_styles', '_s_load_fonts');
```

Typekit code could be something like this (from http://wptheming.com/2013/02/typekit-code-snippet/ ):

```
function _s_typekit() {
    wp_enqueue_script( 'theme_typekit', '//use.typekit.net/xxxxxxx.js');
}
add_action( 'wp_enqueue_scripts', '_s_typekit' );

function _s_typekit_inline() {
  if ( wp_script_is( '_s_typekit', 'done' ) ) { ?>
  	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<?php }
}
add_action( 'wp_head', '_s_typekit_inline' );
```

One is style, other is script. Maybe we could have a Font enqueueing function that had both options commented out? Or just do GoogleFonts?

Thoughts?

cc/ @karmatosed @obenland @ianstewart

**Comment by slushman** [comment]
I do something similar, but in my on starter theme based on _s (along with a pile of other useful functions and basic styling head-starts). I just watch all the changes in _s and keep it up to date when I start a new project.

As far as adding it into _s itself, I'd say that's probably not what they want to do, but I'll happily defer to the maintainers to get their take. I know they've left things like this up to other people before.

**Comment by emiluzelac** [comment]
Few notes if that's all right.

I don't believe that Automattic uses `wp_register_*`, simply because registration is not needed.

Additionally:

- `googleFonts` should be `example-fonts` instead. Checkout [Justin Tadlock's](http://themereview.co/prefix-all-the-things/) post about prefixing.
- You can freely remove `http:` from Google fonts to avoid issues with SSL, or do a custom function to include both.
- `wp_print_styles` [should not](https://make.wordpress.org/core/2011/12/12/use-wp_enqueue_scripts-not-wp_print_styles-to-enqueue-scripts-and-styles-for-the-frontend/) be used for scripts/styles.

**Comment by fklein-lu** [comment]
Please refer [this article](http://themeshaper.com/2014/08/13/how-to-add-google-fonts-to-wordpress-themes/) on how to add Google Fonts correctly to a theme.

I would speak out against inclusion of this in _s:
1. Fonts loaded from a 3rd party CDN are not a standard feature.
2. The code to use differs according to the use case. This is not as easy as just replacing a variable.
3. The code is fairly complicated, and users should refer to an article on how to do this correctly. Like this they maybe learn a thing or two and will become more proficient instead of badly repurposing existing code.

**Comment by philiparthurmoore** [comment]
Yep, this isn't something that belongs in _s. Each loaded font requires a different way of handling it, and there's not one bit of code that will cover all use cases. For something like this I'd leave it up to the default themes to give the best example of how to handle Google fonts.

**Comment by hugobaeta** [comment]
Makes sense. My point was to have something there commented out, to use if needed, not impose something by default.  ;)

@fklein-lu thanks for that article link - that makes sense to me now!
