### ISSUE TITLE
Empty `footer` tag in single page

### ISSUE THREAD

**Issue by ernilambar** [Automattic/_s#779]
We have `footer` tag with class `entry-footer` in `content-single.php`. Inside that function `_s_entry_footer` is called. But there is case when empty value is returned from that function. So our `footer` tag is sitting forever alone there. Is it intentionally done like that that? for SEO purpose may be?

**Comment by philiparthurmoore** [comment]
> But there is case when empty value is returned from that function. 

What case is that? Can you be more specific with this Issue? Where exactly do we need to look in the code to see what you're seeing? In what case will that function end up being an empty footer tag? In which views?

Thanks.

**Comment by obenland** [comment]
> Where exactly do we need to look in the code to see what you're seeing?

https://github.com/Automattic/_s/blob/5bb0534358eb612e9ccec163076aac8869b94c75/inc/template-tags.php#L100-L128

> In what case will that function end up being an empty footer tag?

When the single post viewed is not a post, comments are closed, and the viewing user can't edit it.

> In which views?

All views that use `content-single.php`.

> Is it intentionally done like that that? for SEO purpose may be?

It's not intentional, it just is how it is. I don't have a huge problem with an empty tag. Since this is a starter theme, theme authors could add more functionality there and it could be seen as encouragement for a proper HTML structure.

**Comment by philiparthurmoore** [comment]
Why not just put `<footer class="entry-footer">` inside the function? everywhere it's being used (content, content-single, content-search) just wraps `_s_entry_footer`. Seems cleaner IMO.

**Comment by obenland** [comment]
PR it and let's see how clean it is! :)
I don't think it's a big deal, but I also don't see a reason not to change it.

**Comment by philiparthurmoore** [comment]
Gave it 10 minutes and realized that you're right. Yes, removing `<footer class="entry-footer">` from those template parts is cleaner, but the logic required to bail out on `_s_entry_footer` under current conditions and any future conditions added in by theme authors would make this very messy very quickly. Closing. Thanks @obenland.
