### ISSUE TITLE
Unnecessary roles in header, nav, main and footer

### ISSUE THREAD

**Issue by 11bits** [Automattic/_s#786]
I checked the theme with https://validator.w3.org and according this tool:

- role="banner" and role="contentinfo" are unnecessary for elements that are not descendants of an article element or a section element. 
- Navigation role and main role are not necessary for elements nav and main.

**Comment by davidakennedy** [comment]
Hey @11bits!

Thanks for creating this issue! This is a bit tricky, but after some research, this is where I'm landing as far as our approach in _s for this:

* These errors are definitely valid errors. The advice for explicitly adding landmark roles is changing. See this [post](http://alistapart.com/comments/wai-finding-with-aria-landmark-roles) and [comment](http://alistapart.com/comments/wai-finding-with-aria-landmark-roles#338902).
* I brought this to the WordPress Accessibility team for [other thoughts](https://wordpress.slack.com/archives/accessibility/p1438627360000954).
* Currently, _s supports IE9 and up.
* Internet Explorer is the only major browser that [doesn't support the semantic information via accessibility api](http://www.html5accessibility.com/). But there are bugs filed, so that will likely change in future versions. Maybe Edge? The support is better when the roles are there, especially with a wider range of assistive technology, like screen readers.

Given that we support IE9 and up, I'm inclined to keep the roles explicitly attached to the html5 elements they correspond with because that's better for the users we support with _s. So we'll let the errors in the validator go for now. For what it's worth, we had errors for having `role`s specified for awhile until the validators caught up.

This is an issue we should definitely revisit as support gets better and/or as we drop support for older browsers.

You may want to take the `role`s off for your _s-based project, depending on your browser and assistive technology support.

Thanks again! I'm closing this issue, but if anyone wants to discuss further, just comment, and we'll reopen.
