### ISSUE TITLE
Put 'after_setup_theme' inside if statement

### ISSUE THREAD

**Issue by camskene** [Automattic/_s#788]
Should this add_action be inside the previous if statement?

https://github.com/Automattic/_s/blob/master/functions.php#L79

**Comment by emiluzelac** [comment]
Looks good to me, they can be at the top or bottom

**Comment by fklein-lu** [comment]
Calls to `add_action()`or `add_filter()` should not be inside the `function_exists()` conditional.

This is because when you override the hooked function, the `add_action()`or `add_filter()` call will no longer be accessible. This defeats the purpose of having pluggable functions in the first place.
