### ISSUE TITLE
Themecheck (58%) 78% (navigation)

### ISSUE THREAD

**Issue by B-iggy** [Automattic/_s#836]
Hey,

I checked (http://themecheck.org) the recent master zip and got these results. 58% with a yml file in it. Wayne. But 78% with the missing nav stuff.

What's the right way?
`posts_nav_link() or paginate_links() or next_posts_link() and previous_posts_link()`
or
`the_post_navigation()` (e.g. in single.php)
![bildschirmfoto-1](https://cloud.githubusercontent.com/assets/7815434/10631874/1210beac-77e1-11e5-8921-0b717aaec490.png)

![bildschirmfoto-2](https://cloud.githubusercontent.com/assets/7815434/10631879/16a05e6e-77e1-11e5-9363-f85c52b678ce.png)

**Comment by sarahmonster** [comment]
Hi there, 

`the_post_navigation()` used in single.php for navigation between individual post pages. `the_posts_navigation()` is used on archive pages to paginate between pages of posts.

These functions have been available in core since WordPress 4.1.0, and effectively give a standardised markup for post navigation. If you have a look at the source code, `the_posts_navigation` uses `get_previous_posts_link()` to generate its output. You may wish to use different navigation functions for your themes if you require fine-grained control over your markup, but in most cases these functions are the most straightforward choice.

Themecheck.org is a fork of the original Theme Check plugin (https://wordpress.org/plugins/theme-check/) used by the WordPress.org repository, and doesn't appear to have been updated since June 2014. (https://github.com/themecheck/themecheck) It may not be up-to-date with current WordPress standards. 

Cheers!

**Comment by themecheck** [comment]
We updated themecheck.org about this a few days ago
