### ISSUE TITLE
Removing the font-size from body tag

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [Automattic/_s#869]
**Line number 269**, in **style.css** rule:
body, button, input, select, textarea
needs to remove the line **font-size: 1rem;**, as this is creating problems.

**Comment by sarahmonster** [comment]
Hi there! What sort of problems, specifically, is this creating? I typically leave this in my themes—and use rems for all font-size units—and find it works nicely, so I suspect it may be theme-specific, rather than something we should change in _s as a whole. 

For theme support and development help, please head over to https://wordpress.org/support/forum/themes-and-templates. :)

**Comment by kashifullahwebdeveloper** [comment]
I didn't find any clue, but when I remove **font-size: 1rem;** from line number 269 in style.css all the body font set to default, else the font size become very small.

I have created my own custom theme and that might be the problem with it.
Anyway, thankful for the help :)

**Comment by sarahmonster** [comment]
You're very welcome!
