### ISSUE TITLE
PCLZIP_ERR_BAD_FORMAT when downloading from Underscores.me

### ISSUE THREAD

**Issue by eriktdesign** [Automattic/_s#903]
I'm not sure if this repo is the place to put this, but here we go...

When using WP-CLI or wget to download a theme from underscores.me like this:
`wp theme install http://underscores.me/?underscoresme_generate=1&underscoresme_name=SITENAME`
`wget -O kansasfpc.zip http://underscores.me/?underscoresme_generate=1&underscoresme_name=SITENAME`

It doesn't work. I get the following error message: 
`Warning: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`

Any thoughts? I was hoping to really automate my jumping-off process, but this is a bit of a hurdle.

**Comment by davidakennedy** [comment]
Hey there @eriktdesign!

Thanks for filing this issue. Can you file here instead?

https://github.com/Automattic/underscores.me/

That repo has the functionality that handles the generation of theme zips for _s, and is a better home for this issue.

I'll look into it, but it may be because of the way we build the zip file.

**Comment by eriktdesign** [comment]
Thanks David, dropping it there.
