### ISSUE TITLE
Pluggable Functions

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#929]
I was wondering why `_s` is using pluggable functions? I personally find WordPress template system, hooks and filters better way of doing modifications via child theme or functionality plugin.

**Comment by devinsays** [comment]
My guess is that pluggable functions are used because they are more approachable for new developers. It took me a while to wrap my head around actions/filters versus just directly modifying the code when I first started developing with theme frameworks.

There's only four pluggable functions I see (including _s_setup which is an action and pluggable). I assume the ones you'd suggest converting to actions are _s_posted_on and _s_entry_footer?

**Comment by samikeijonen** [comment]
I would not use pluggable functions at all. `_s_posted_on` and `_s_entry_footer` functionality can can be in their own template files.

For example there can be `entry-meta.php` file where you call the needed functions `posted_on` function.

> My guess is that pluggable functions are used because they are more approachable for new developers.

Could be but that's why we are here to help and educate.

**Comment by mrwweb** [comment]
After a lot of thought, I've realized that it's probably so a new _s theme can be a good parent theme once built. If someone can confirm that, I think a comment would be in order, as I've puzzled over this in path.

Otherwise, I think pluggable functions are wrong for _s with the exception of functions that replicate new core functionality (like `the_archive_title()` until recently). Since _s is a starter theme and not intended to be a parent theme, I think pluggable functions imply otherwise and might actually lead an experienced WordPress developer astray.

To use `_s_setup()` as an example, that function is one of the most foundational functions to the nature of the theme and so I just can't imagine a situation in which it's overridden rather than just edited (unless it's a future child theme issue).

**Comment by sixhours** [comment]
> After a lot of thought, I've realized that it's probably so a new _s theme can be a good parent theme once built. If someone can confirm that, I think a comment would be in order, as I've puzzled over this in path.

That's the idea. _s *itself* isn't intended to be used as a parent theme, but themes based on _s are often used as parent themes.

**Comment by samikeijonen** [comment]
> That's the idea. _s itself isn't intended to be used as a parent theme, but themes based on _s are often used as parent themes.

I was kind of waiting for that answer:) But for me it doesn't answer the **why** question. Then again it could be just me:)

**Comment by mrwweb** [comment]
I think @samikeijonen is on to something. The intention seems good, but I think it makes more sense to let developers decide which functions are pluggable. And as Sami said, replacing a few of the existing pluggable functions with template parts could be more developer friendly and just as child-theme friendly.

**Comment by karmatosed** [comment]
I stand by what @sixhours has said. This isn't a parent theme and as result this is ok. If you want to take the pluggable approach you can even fork _s. The point is it's the basics not fits everyone.
