### ISSUE TITLE
SCSS Linting

### ISSUE THREAD

**Issue by peiche** [Automattic/_s#936]
Since Underscores' stylesheet is generated by Sass, would it be beneficial to have a scss-lint configuration file?

**Comment by jaakkolehtonen** [comment]
Ive been using [stylelint](http://stylelint.io/) and it's been create since it has [config](https://github.com/ntwb/stylelint-config-wordpress) for wp's css coding standards. Cool thing is it lint's both css and scss!

**Comment by anagio** [comment]
Leave it out, because people who have dev environments already setup with grunt, gulp etc will likely have linters already setup from past projects. If they want to use stylelint they can add it. For anyone not linting it's an extra file in the code base that's taking up space. And if it did get added, what's next jslint? This is a minimal bare bones starter theme it should stay that way without any extras.

**Comment by jrfnl** [comment]
> And if it did get added, what's next jslint?

That's actually already included in the Travis run - see #888

**Comment by karmatosed** [comment]
I would vote no as it's up to each person.

**Comment by peiche** [comment]
Do the Underscores team not lint their SCSS/CSS as they add or edit it?

**Comment by karmatosed** [comment]
How we each choose to do things is our own. If you are asking at Automattic what we do, we have no one method and allow the themer to chose their path. As I am saying should happen here.
