### ISSUE TITLE
Comments are XSS vulnerable

### ISSUE THREAD

**Issue by iamandrewluca** [Automattic/_s#941]
While testing **_s** for first time, I tried to add in a comment this line
`<script>location.href = 'http://example.com';</script>`
And it worked! Comments are **XSS** vulnerable. This is the behaviour for this starter theme, or should be a fix for it.
Thanks!

**Comment by grappler** [comment]
I tested this with a anonymous user and the script was sanitized. The script was only run when the user is an administrator. I believe that WordPress allows Admins to unfiltered HTML. If there was an issue then I expect it would be with WordPress and not the theme as `_s` uses core features.

Security issues should not be reported in a public place like GitHub issues as there is no time for the developers to fix the issue. You should have reported the issue here: https://hackerone.com/automattic

**Comment by iamtakashi** [comment]
@grapper is correct. This only can happen when stuff like that posted by admin.

**Comment by iamandrewluca** [comment]
Thanks!
