### ISSUE TITLE
Fatal Error?

### ISSUE THREAD

**Issue by AvaLiJade** [Automattic/_s#946]
I'm not a developer so forgive me if this is not the right place for posting this. But a designer posted a cool theme based on _s to the repository and I was trying it out. I started a few threads there but he didn't seem to really know what's going on either. While I'm not sure if this is an issue with his theme or the _s base, I got a funky error when I used the QUOTE post-format and forgot to include something in blockquote tags. I was using a child theme and the theme he made was called Creative Blog.  

Catchable fatal error: Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given, called in (mypath)/wp-content/themes/creative-blog/template-parts/content-quote.php on line 13 and defined in (mypath)/wp-content/themes/creative-blog/inc/extras.php on line 665

I replaced my directory names with (mypath)

This appeared on http://(mydomain)/category/articles archives pages where the post should be. So I'm not sure if it's an issue in the framework or his rendition thereof, but I thought I'd tell someone.

**Comment by jrfnl** [comment]
> So I'm not sure if it's an issue in the framework or his rendition thereof,

@AvaLiJade I understand that as non-developer, it's hard to gauche where a problem comes from and that you 'just' want it solved.

Unfortunately in this case, this really is not the place as the issue is specific to the rendition of Creative Blog and has nothing to do with `_s`.

If you look in the [_s/template-parts](https://github.com/Automattic/_s/tree/master/template-parts) directory in this repo, you will see that the base does not contain a `content-quote.php` template. Also, if you look in [_s/inc/extras.php](https://github.com/Automattic/_s/blob/master/inc/extras.php), you will see no reference to any of the [`DOM`](http://php.net/manual/en/book.dom.php) group of functions.
So the issue does not come from `_s`.

So, I'm sorry, but in this case, the developer of the Creative Blog theme is your best bet. They may want to read up on the [`DOM`](http://php.net/manual/en/book.dom.php) group of functions to understand how to fix their problem code.

**Comment by alaczek** [comment]
Hi @AvaLiJade!
As @jrfnl said, contacting the theme developer via WordPress.org forums is your best bet to get this issue sorted.

**Comment by AvaLiJade** [comment]
I went there and posted but they have posts there with a link to here saying post here.

**Comment by AvaLiJade** [comment]
Okay thanks
