### ISSUE TITLE
Domain name in enqueue

### ISSUE THREAD

**Issue by DavidArturoPatinoDePablo** [Automattic/_s#955]
The domain name used for the java script files are not over written with the domain name for the theme. 
Found the original domain name of the 2015 domain in place, ie 20151215.
File functions.php

**Comment by laurelfulford** [comment]
Hi @DavidArturoPatinoDePablo!

The "20151215" is the version number for the enqueued file - please see: https://developer.wordpress.org/reference/functions/wp_enqueue_script/

The formatting in _s uses the date the file was added (Dec 15, 2015) - you can also switch it to use numbers (like "1.0.1"). The version numbers can be incremented when you make a change to one of your enqueued files, to make sure the old version isn't being cached.

I'm going to close this since it's not an issue with the theme, but please comment if you have any further questions at all!
