### ISSUE TITLE
using the function _s_posted_on() outside the loop

### ISSUE THREAD

**Issue by saltnpixels** [Automattic/_s#958]
Based on another issue I had before of outputting article info outside the loop, I was trying to output the meta outside the loop too.
I wanted to use the function that comes with underscores _s_posted_on();
For the most part this works fine. 
All the template tags in there default to the current post like getting the date and stuff.

The only problem is the author does not show up because it needs to be in the loop.
I fixed it, but I am not sure this counts as an issue or just my project... :)

I'm new around here....
Anyways you can replace it with this, and now you can use the funciton in or outside the loop.
```
global $post;
$author_id = $post->post_author;

$byline = sprintf(
   esc_html_x( 'by %s', 'post author', 'seasaltpress' ),  
  '<span class="author vcard"><a class="url fn n" href="' . esc_url( get_author_posts_url( get_the_author_meta( 'ID', $author_id ) ) ) . '">' . esc_html( get_the_author_meta( 'nickname', $author_id ) ) . '</a></span>'
	);
```

**Comment by davidakennedy** [comment]
Hey @saltnpixels!

Welcome! Thanks for filing this issue. That's a good way to modify the function if you need it outside of the loop, and perfectly valid. But I don't think the function in _s needs to be changed because most wouldn't need to use it that way, and if themers need to, they can make the modification as you have.

Cheers!
