### ISSUE TITLE
Remove Post Format Support

### ISSUE THREAD

**Issue by khacoder** [Automattic/_s#966]
I am continuously seeing themes where the author has not paid any attention to Post Formats.

The only post format supported in any way in the default _s setup is the Aside post format, as the title is not showing in the blog index.

The other post formats; image, video, quote, and link are not supported.

Themes approved and set live this way provide a bad user experience as users select one of the post formats and nothing happens.

**Comment by sixhours** [comment]
I'd be cool with getting rid of post format support/styles in _s, personally.

**Comment by karmatosed** [comment]
Totally +1'ing this and I've merged it - thanks.

**Comment by khacoder** [comment]
awesome :)

**Comment by philiparthurmoore** [comment]
Did .com stop requiring the five basic post formats per theme?

(I like this PR.)

**Comment by sixhours** [comment]
@philiparthurmoore  Yep. :)

**Comment by philiparthurmoore** [comment]
Very cool.

**Comment by wilchak** [comment]
Actually, I found it very useful to have the add_theme_support('post-formats') stuff included out of the box, because I always use it when developing client sites.

I can understand the case for removing it (because unaware developers were just not implementing the templates) and causing a bad experience for the users, but since post formats are such a great WP user-facing feature, I think it makes more sense to keep this code in underscores to promote the functionality to developers who wouldn't otherwise build support in. 

Perhaps you could keep it in functions.php, just commented out?
