### ISSUE TITLE
Visual Editor buggy once _s is activated.

### ISSUE THREAD

**Issue by TheAveragewebGuy** [Automattic/_s#969]

**Comment by karmatosed** [comment]
@TheAveragewebGuy I'm sorry things aren't working. However, this wouldn't be due to _s. It more than likely is due to plugins or any additions. For now, I am going to close this. If after moving all plugins there is still an issue, I would suggest checking you've not added any code to _s. If you haven't then please do let us know and we may be able to give more insight with some steps.

**Comment by TheAveragewebGuy** [comment]
You are right, I didnt remember I've added `remove_filter( 'the_content', 'wpautop' );` to funtions.php.
Thanks!
