### ISSUE TITLE
Font-size mixin - a suggestion

### ISSUE THREAD

**Issue by codesipro** [Automattic/_s#973]
Hi, I've been playing around with the font-size mixin, and found that although the mixin generates the correct px value for the fallback, no matter how I adjust the variables, browsers that use rems compute the 1 rem value to be 16px.

Is there any merit in changing the second line of the mixin to something like the following?

// Rem output with px fallback
@mixin
font-size($sizeValue: 1) {
**font-size: ($sizeValue \* 1) \* $font-base;**
font-size: $sizeValue \* 1rem;
}
- with the $font-base variable defined in px, and font-size: $font-base assigned to the html tag in the typography partial.

This way the base font size can be altered in one place, and scaling by rems will work with the desired value on new browsers and fall back to the correct px value for older ones.

**Comment by philiparthurmoore** [comment]
Does anyone have any feedback on this? I have no horse in this race.

**Comment by joshmcrty** [comment]
That's the correct behavior. 1 rem _is_ 16px in pretty much all browsers because their default font size is 16px.

There is a potential accessibility issue with setting `font-size` in px on the `html` element. For example, if you go into Chrome settings and under the "Show advanced settings" section change the Font size to "Large" this will not work if the `html` element has a `font-size` specified in px.

![image](https://cloud.githubusercontent.com/assets/1522068/18812928/fc25505c-8299-11e6-87fe-c8b75d586c3b.png)

Firefox has a similar setting that would be nullified. I'm not sure about other browsers.

Back in the day when using `em`s became more mainstream I saw a lot of websites set the `html` `font-size` to 62.5% so that 1em = 10px for easier math, and using a percentage doesn't nullify the browsers' default font size setting--it just bases the percentage on it. You could do something like that, then you'd be able to use the mixin like this:

``` css
body: {
  @include font-size(1.6); // 16px
}
```

This would be 16px for users with default browser font sizes, and for users who set their default browser font size to something else, it would be that size. It effectively makes the math easier when writing the CSS. But you'd have to modify the mixin to multiply the size by 10 instead of 16 for the pixel fallback in this example.

Hopefully my math is correct here :)

**Comment by davidakennedy** [comment]
Thanks for opening this issue @fingermonster!

I'd be open to a change here as long as it doesn't set the font size of the `html` tag in `px` because that does create accessibility problems as @joshmcrty mentioned. Maybe the mixin could be altered to account for that? PRs welcome! 😄

**Comment by m-e-h** [comment]
Why not just remove the `px` fall back? `rem` is supported in ie9 and up.
If for some reason we want ie8 support just change the 4 places where `rem` is used, to `em`.
We want less code, not more, right?

**Comment by davidakennedy** [comment]
I wouldn't be opposed to removing the `px` fallback. But I also don't think it's too much effort to have it there. If any device that doesn't support `rem`, it would fall back to the browser default, I believe. Which would be all one size, and probably alter the design considerably. So I think the fallback is smart in this case, no matter what browser support is.

**Comment by joyously** [comment]
I think a better solution is to remove all font rules (outside of normalize) except for one saying
`html {font-size: 100%}`
The browser defaults are quite good, and normalize fixes the few problems. Using `rem` actually causes more problems without any benefits. I've seen so many themes with tiny `<code>` or `<pre>` because Bootstrap uses `rem` on them and `html {font-size: 10px}` to make the math easy.
Keep it simple by removing it all.

**Comment by philiparthurmoore** [comment]
@crunnells Can you please elaborate on why you added the Suggest Close label? Doing a sweep through issues at the moment and looking for opportunities to clean up. Thank you.
