### ISSUE TITLE
diffs between _s and component variants

### ISSUE THREAD

**Issue by MichaelCalleia** [Automattic/_s#979]
Recently found the component variants of _s and noticed a number of diffs—mostly in code structure more so than content.

These differences should not have an impact on functionality, but will have a negative impact on learning curve for some.

Any objection to removing these differences in how the themes are organized and removing the differences?

In addition, the users of the component variants would greatly benefit from an expanded explanation (including code comments) to describe what is added or removed from each variant. This will help people pick the right theme and better understand how to mix and match bits they need.

If there is something I can do to contribute and help with any of the above, please let me know.

**Comment by davidakennedy** [comment]
Hey @MichaelCalleia,

Thanks for filing this issue.

> Any objection to removing these differences in how the themes are organized and removing the differences?

There are a lot of differences because the projects are very different. That's worth keep in mind, as some of the differences are there for a reason. That said, issues and pull requests are always welcome! The two projects don't and shouldn't stay in sync, except when it comes to theming or development best practices.

It's best to file the issues over at the theme components repo and be as specific as possible. See: https://github.com/Automattic/theme-components/issues
