### ISSUE TITLE
Possible enhancement: Add <span> tags to Archive page titles

### ISSUE THREAD

**Issue by chad1008** [Automattic/_s#983]
There are times when it's helpful to be able to modify archive page titles with CSS - a lot of people want to hide the `Category:` part of a `Category: Press Releases` title for example.

If we added `<span>` tags to the two parts of that string by filtering `get_the_archive_title()` that kind of modification would be possible.

Any thoughts on potential drawbacks to that?

**Comment by sarahmonster** [comment]
I made [https://wordpress.org/plugins/nix-prefix/](a plugin for this) that might be helpful in this context, either to add to _s or to implement on a per-site or per-theme basis. I'm not sure if _s would be the place to introduce this functionality—it would be great to see it in core, though.

[https://github.com/sarahmonster/nix-prefix/blob/master/nix-prefix.php](The code) is pretty simple—it just uses a regex to wrap any string followed by a colon in span tags—but would likely need further testing in order to ensure it didn't potentially introduce any complications.

**Comment by chad1008** [comment]
That looks like it'd do the trick :)

@mendezcode and I were kicking this around the other day and he came up with this (it's a much better approach than my first pass at it was!). It's similar to yours, - but adds `spans` to both halves of the title:

```php
//Filter get_the_archive_title() to add a span to archive and category titles

function my_archive_title( $title ) {
	$parts = explode( ':', $title );
	if ( count( $parts ) > 1 ) {
		$label = array_shift( $parts );
		$parts = implode( ':', $parts );
		$title = sprintf( '<span class="archive-label">%s: </span><span class="archive-title">%s</span>', $label, $parts );
	}
	return $title;
}
add_filter( 'get_the_archive_title', 'my_archive_title' );
```

**Comment by philiparthurmoore** [comment]
Sounds like this would be a good enhancement and also Core proposal. This comes up a lot.

**Comment by satcreative** [comment]
Excellent. +1 to that.

**Comment by karmatosed** [comment]
If this is wanted to be in, we need a PR - anyone up for that?

**Comment by chad1008** [comment]
Looks like there's now a core patch for this: https://core.trac.wordpress.org/ticket/38545

**Comment by davidakennedy** [comment]
I love this suggestion but am going to close this out in favor of the core ticket. It's better if it happens there. Thanks for raising this @chad1008!
